### ISSUE TITLE
Do you want logo?

### ISSUE THREAD

**Issue by vasifalibeyli** [duangsuse/attrtools#2]
Hi,
I am graphic designer. I would like to prepare a logo for your application.
If you accept I can prepare this logo for you with great pleasure.
I wait for your response.

**Comment by duangsuse** [comment]
@vasifalibeyli Maybe I want one, thank you :smiley:

**Comment by vasifalibeyli** [comment]
of course. Coming soon :) :D

**Comment by vasifalibeyli** [comment]
![logo](https://user-images.githubusercontent.com/41432961/43397516-3cd78b8a-9416-11e8-9fd4-2796f108b86c.png)

Best regards
Vasif Alibeyli

**Comment by vasifalibeyli** [comment]
do you like it?

**Comment by duangsuse** [comment]
@vasifalibeyli Yes, but attrtools is just a command-line utility, it cannot have an icon :)
Maybe I can use this elsewhere if I want

[Android frontend] have icons, but I want to make the app smaller so I don't want to add an icon lol

**Comment by vasifalibeyli** [comment]
If you want something, I can prepare something for it.

**Comment by duangsuse** [comment]
> If you want something, I can prepare something for it.

Thank you, but I don't want logos now

**Comment by vasifalibeyli** [comment]
Ok. Thanks
